#!/usr/bin/env python3
"""
Canonicalize section titles and set section_id = {document_id}_section_{number}
Applies edits to:
- backend/evaluation/dataset/new_qa_pairs.json
- backend/evaluation/results/new_answer_results.json

Mapping:
  Introduction -> 1 Introduction
  Ordinary PCR -> 2 Ordinary PCR
  Hard PCR -> 3 Hard PCR
  Other PCR -> 4 Other PCR Tasks
  Conclusion -> 5 Conclusion

Any unmatched title is left as-is but gets an autogenerated section_id with number 0.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
QA_PATH = ROOT / 'backend' / 'evaluation' / 'dataset' / 'new_qa_pairs.json'
ANS_PATH = ROOT / 'backend' / 'evaluation' / 'results' / 'new_answer_results.json'

def canonicalize(title):
    if not title:
        return None
    t = title.lower()
    if 'introduction' in t:
        return '1 Introduction'
    if 'ordinary' in t:
        return '2 Ordinary PCR'
    if 'hard' in t:
        return '3 Hard PCR'
    if 'other' in t or 'other pcr' in t or 'other pcr tasks' in t:
        return '4 Other PCR Tasks'
    if 'conclusion' in t:
        return '5 Conclusion'
    # fallback: keep original
    return title

def section_number_from_title(title):
    if not title:
        return 0
    parts = title.split()
    try:
        n = int(parts[0])
        return n
    except Exception:
        return 0

def main():
    qa = json.loads(QA_PATH.read_text())

    # Update QA file entries
    for entry in qa:
        orig = entry.get('section_title')
        canon = canonicalize(orig)
        if canon is not None:
            entry['section_title'] = canon
        # set section_id
        docid = entry.get('document_id', '')
        num = section_number_from_title(entry.get('section_title'))
        entry['section_id'] = f"{docid}_section_{num}"

    QA_PATH.write_text(json.dumps(qa, indent=2, ensure_ascii=False))
    print(f"Wrote {QA_PATH}")

    # Build question -> section mapping
    qmap = {e['question']: (e['section_id'], e.get('section_title')) for e in qa}

    # Update answer results
    ans = json.loads(ANS_PATH.read_text())
    for sample in ans.get('per_sample_results', []):
        q = sample.get('question')
        if q in qmap:
            sid, stitle = qmap[q]
            sample['section_id'] = sid
            sample['section_title'] = stitle
        else:
            # if not found, leave as-is but ensure section_id format
            docid = sample.get('section_id', '')
            if docid and '_section_' not in str(docid):
                sample['section_id'] = f"{docid}_section_0"

    ANS_PATH.write_text(json.dumps(ans, indent=2, ensure_ascii=False))
    print(f"Wrote {ANS_PATH}")

if __name__ == '__main__':
    main()
